### PR TITLE
Using a timer to deactivate motion alarm on sensor

### PR DESCRIPTION
**Pull request by MarcoFuykschot**
A fix for #9

### CODE REVIEW

**Comment by steffjenl** [comment]
When I am back I will look at it

**Comment by MarcoFuykschot** [comment]
> When I am back I will look at it

Sure thanks,

**Comment by steffjenl** [comment]
@MarcoFuykschot can you change the functions to this.homey.setTimeout and this.homey.clearTimeout ? Thanks

https://apps.developer.homey.app/upgrade-guides/upgrading-to-sdk-v3#managercron-removal

**Comment by steffjenl** [comment]
Sorry, I have already fixed see https://github.com/steffjenl/com-homey-unifiprotect/blob/bug-fix-motionalarm-sensor/drivers/protectsensor/device.js thanks for the fix!

**Pull request merged**
